version: "2"
services:
  app:
      container_name: app
      restart: always
      image: jithinchowdary/todo_app:latest
      ports:
        - "5000:5000"
      depends_on:
        - mongodb
      links:
        - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"